apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-end
  name: front-end-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/front-end-svc
spec:
  ports:
  - port: 8100
    protocol: TCP
    targetPort: 4200
  selector:
    app: front-end
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}