apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-feeds-api
  labels:
    app: udagram-feeds-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-feeds-api
  template:
    metadata:
      labels:
        app: udagram-feeds-api
    spec:
      containers:
      - name: udagram-feeds-api
        image: gzamorasosa12/udagram-feeds-api
        ports:
        - containerPort: 8080
